#!/bin/sh
set -eu

: "${PLATFORM_ENV:=production}"
: "${PLATFORM_IDENTITY_URL:=}"
: "${PLATFORM_TENANT_URL:=}"
: "${PLATFORM_AUTHORIZATION_URL:=}"
: "${PLATFORM_APPLICATION_URL:=}"
: "${PLATFORM_AUDIT_URL:=}"
: "${PLATFORM_CONFIG_URL:=}"
: "${PLATFORM_NOTIFICATION_URL:=}"
: "${PLATFORM_FILE_URL:=}"
: "${PLATFORM_SCHEDULER_URL:=}"
: "${PLATFORM_DICTIONARY_URL:=}"
: "${PLATFORM_SERVICE_REGISTRY_URL:=}"
: "${PLATFORM_WEBHOOK_URL:=}"
: "${PLATFORM_WORKFLOW_URL:=}"
: "${PLATFORM_SEARCH_URL:=}"
: "${PLATFORM_METERING_URL:=}"
: "${PLATFORM_BILLING_URL:=}"
: "${PLATFORM_RULE_URL:=}"
: "${PLATFORM_DATA_EXPORT_URL:=}"
: "${PLATFORM_IMPORT_URL:=}"
: "${PLATFORM_SWAGGER_URL:=}"

if [ "$PLATFORM_ENV" = 'production' ]; then
  for service_url in "$PLATFORM_IDENTITY_URL" "$PLATFORM_TENANT_URL" "$PLATFORM_AUTHORIZATION_URL" "$PLATFORM_APPLICATION_URL"; do
    if [ -z "$service_url" ]; then
      echo 'core platform service URLs are required in production' >&2
      exit 1
    fi
  done
fi

export PLATFORM_ENV PLATFORM_IDENTITY_URL PLATFORM_TENANT_URL PLATFORM_AUTHORIZATION_URL PLATFORM_APPLICATION_URL PLATFORM_AUDIT_URL PLATFORM_CONFIG_URL PLATFORM_NOTIFICATION_URL PLATFORM_FILE_URL PLATFORM_SCHEDULER_URL PLATFORM_DICTIONARY_URL PLATFORM_SERVICE_REGISTRY_URL PLATFORM_WEBHOOK_URL PLATFORM_WORKFLOW_URL PLATFORM_SEARCH_URL PLATFORM_METERING_URL PLATFORM_BILLING_URL PLATFORM_RULE_URL PLATFORM_DATA_EXPORT_URL PLATFORM_IMPORT_URL PLATFORM_SWAGGER_URL
envsubst '${PLATFORM_ENV} ${PLATFORM_IDENTITY_URL} ${PLATFORM_TENANT_URL} ${PLATFORM_AUTHORIZATION_URL} ${PLATFORM_APPLICATION_URL} ${PLATFORM_AUDIT_URL} ${PLATFORM_CONFIG_URL} ${PLATFORM_NOTIFICATION_URL} ${PLATFORM_FILE_URL} ${PLATFORM_SCHEDULER_URL} ${PLATFORM_DICTIONARY_URL} ${PLATFORM_SERVICE_REGISTRY_URL} ${PLATFORM_WEBHOOK_URL} ${PLATFORM_WORKFLOW_URL} ${PLATFORM_SEARCH_URL} ${PLATFORM_METERING_URL} ${PLATFORM_BILLING_URL} ${PLATFORM_RULE_URL} ${PLATFORM_DATA_EXPORT_URL} ${PLATFORM_IMPORT_URL} ${PLATFORM_SWAGGER_URL}' \
  < /usr/share/nginx/html/platform-config.js.template \
  > /usr/share/nginx/html/platform-config.js
